<!--<script src="--><?php //echo base_url()?><!--public/assets/js/admin.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/demo.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/fullscreen.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/pages/blog/blog.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/pages/calendar/calendar.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/pages/cards/basic.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/pages/colored.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/charts/chartjs.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/charts/flot.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/charts/jquery-knob.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/charts/morris.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/charts/polar_area_chart.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/file/filemanager.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/forms/advanced-form-elements.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/forms/basic-form-elements.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/forms/form-wizard.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/maps/google.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/forms/jvectormap.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/medias/image-gallery.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/tables/editable-table.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/tables/footable.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/tables/jquery-datatable.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/animations.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/dialogs.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/modals.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/notifications.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/range-sliders.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/sortable-nestable.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets/ecommerce.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets/index.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/sortable-nestable.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/sortable-nestable.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/ui/sortable-nestable.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets/infobox/infobox-3" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets/infobox/infobox-2.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets/infobox/infobox-3.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets/infobox/infobox-2.js" type="text/javascript"></script>-->
<!--<script src="--><?php //echo base_url()?><!--public/assets/js/pages/widgets/infobox/infobox-1.js" type="text/javascript"></script>-->
<!---->
<!---->
